### ISSUE TITLE
Getting Unauthorized errors lately

### ISSUE THREAD

**Issue by patrik-malina** [carleeno/elevenlabs_tts#123]
## System Information

version | core-2024.6.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Belgrade
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 32

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 19.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2024.5.5), File editor (5.8.0), Frigate Proxy (1.5), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.1), Node-RED (17.0.13), Samba share (12.3.1), Zigbee2MQTT (1.38.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 17
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 2, 2024 at 21:35
-- | --
current_recorder_run | June 8, 2024 at 11:43
estimated_db_size | 4138.11 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Recently mine elevenlabs TTS stopped working. Checked on their site, I have enough quota.
Tried to renew API key, also not working.
Im usig it from Node-red. But also when tried on developer services, getting same error.  

### Reproduction steps

Call TTS speak service

### Debug logs

```text
2024-06-08 13:48:46.070 DEBUG (MainThread) [custom_components.elevenlabs_tts.elevenlabs] Looking for voice with identifier Jeremy
2024-06-08 13:48:46.070 DEBUG (MainThread) [custom_components.elevenlabs_tts.elevenlabs] Found voice bVMeCyTHy58xNoL34h3p from identifier Jeremy
2024-06-08 13:48:46.071 DEBUG (MainThread) [custom_components.elevenlabs_tts.elevenlabs] Requesting TTS from text-to-speech/bVMeCyTHy58xNoL34h3p
2024-06-08 13:48:46.071 DEBUG (MainThread) [custom_components.elevenlabs_tts.elevenlabs] Request data: {'text': '"Vitaj, kráľovná prachoviek a mopov!"', 'model_id': 'eleven_multilingual_v2', 'voice_settings': {'stability': 0.5, 'similarity_boost': 0.75, 'style': 0.2, 'use_speaker_boost': True}}
2024-06-08 13:48:46.071 DEBUG (MainThread) [custom_components.elevenlabs_tts.elevenlabs] Request params: {'optimize_streaming_latency': 0}
2024-06-08 13:48:46.477 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 1037, in get
    content, data = await self.tts.async_read_tts(filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 892, in async_read_tts
    await pending
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 731, in get_tts_data
    extension, data = await engine_instance.internal_async_get_tts_audio(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 465, in internal_async_get_tts_audio
    return await self.async_get_tts_audio(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elevenlabs_tts/tts.py", line 118, in async_get_tts_audio
    return await self._client.get_tts_audio(message, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elevenlabs_tts/elevenlabs.py", line 148, in get_tts_audio
    resp = await self.post(endpoint, data, params, api_key=api_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elevenlabs_tts/elevenlabs.py", line 90, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://api.elevenlabs.io/v1/text-to-speech/bVMeCyTHy58xNoL34h3p?optimize_streaming_latency=0'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
```

**Comment by carleeno** [comment]
Hi @patrik-malina , I'm unable to reproduce using the same voice and parameters. Maybe there's some additional issue with your elevenlabs account.

Try to reproduce the same request directly on their API reference (you can make requests there, add your key to the header, voice id to path, and params to the body) and see if it also returns a 401, if so it may have an explanation of the error.
[https://elevenlabs.io/docs/api-reference/text-to-speech](https://elevenlabs.io/docs/api-reference/text-to-speech)

**Comment by patrik-malina** [comment]
Hm, it seems I spent all characters
![image](https://github.com/carleeno/elevenlabs_tts/assets/73561855/e4c6210a-c214-430e-ba19-5b1078717e6f)

Although it says in first page I have more free quotas
![image](https://github.com/carleeno/elevenlabs_tts/assets/73561855/20ba741b-b07d-46bd-8e52-c9094467b489)

Will see in 4 days.

**Comment by carleeno** [comment]
That'll do it, the "Quota remaining: 5" means you only can generate from 5 more characters. If you send a request with more than 5 characters it will fail.
